### ISSUE TITLE
The “Subscribing to state changes” example in the README appears to use an older subscription API and does not work with `aiovantage==0.22.8`.

### ISSUE THREAD

**Issue by moithepro** [loopj/aiovantage#382]
### Checklist

- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The README currently shows:

```python
def on_load_state_change(event, load, data):
    print(f"{load.name} is at {load.level}%")

async with Vantage("hostname", "username", "password") as vantage:
    vantage.loads.subscribe(on_load_state_change)
    await vantage.loads.initialize()
```

Running this code produces:

```text
TypeError: EventDispatcher.subscribe() missing 1 required positional argument: 'callback'
```

## Cause

In `aiovantage==0.22.8`, `EventDispatcher.subscribe()` has the following signature:

```python
subscribe(event_type, callback)
```

The callback receives a single typed event object instead of the three arguments shown in the README.

For load updates, the event type is `ObjectUpdated`, and the load is available through `event.obj`.

## Suggested documentation update

```python
from aiovantage import Vantage
from aiovantage.events import ObjectUpdated


def on_load_state_change(event: ObjectUpdated):
    load = event.obj
    print(f"{load.name} is at {load.level}%")


async with Vantage("hostname", "username", "password") as vantage:
    vantage.loads.subscribe(ObjectUpdated, on_load_state_change)
    await vantage.loads.initialize()
```

If the example is intended to keep listening as a standalone program, it could also include a complete runnable example:

```python
import asyncio

from aiovantage import Vantage
from aiovantage.events import ObjectUpdated


def on_load_state_change(event: ObjectUpdated):
    load = event.obj
    print(f"{load.name} is at {load.level}%")


async def main():
    async with Vantage("hostname", "username", "password") as vantage:
        vantage.loads.subscribe(ObjectUpdated, on_load_state_change)
        await vantage.loads.initialize()

        print("Listening for load changes. Press Ctrl+C to exit.")
        await asyncio.Event().wait()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
```

## Environment

- `aiovantage`: 0.22.8
- Python: 3.11
- Operating system: Windows

## Additional context

The current README example appears to describe an earlier event API, while the installed release uses typed event objects. Updating the example would prevent users from encountering the missing `callback` argument error

### Reproduction steps

1.
2.
3.
...
